steps:
  # Build and push the image using Buildx
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "-c"
      - |
        docker buildx create --name mybuilder --use
        docker buildx build \
          --platform linux/amd64,linux/arm64 \
          -t us-central1-docker.pkg.dev/agentsea-dev/guisurfer/surfkit-ui:$SHORT_SHA . \
          --push \
          --cache-from=type=registry,ref=us-central1-docker.pkg.dev/agentsea-dev/guisurfer/surfkit-ui:cache \
          --cache-to=type=registry,ref=us-central1-docker.pkg.dev/agentsea-dev/guisurfer/surfkit-ui:cache,mode=max \
          ./ui/surfkit
        if [ "$BRANCH_NAME" == "main" ]; then
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            -t us-central1-docker.pkg.dev/agentsea-dev/guisurfer/surfkit-ui:latest . \
            --push \
            --cache-from=type=registry,ref=us-central1-docker.pkg.dev/agentsea-dev/guisurfer/surfkit-ui:cache \
            --cache-to=type=registry,ref=us-central1-docker.pkg.dev/agentsea-dev/guisurfer/surfkit-ui:cache,mode=max \
            ./ui/surfkit
        fi

# Removed the images field
timeout: "1200s"
